# Site settings
title: Yuu Dev
description: My personal website!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yuudev.tk" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yuu
user_description: I'm a Node.js developer focusing on discord.js to develop discord bots!
user_title: Discord Bot Developer
email: jmquimosing@gmail.com
twitter_username: yuu9937
github_username:  yuu0007
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
